"""baseline schema

Revision ID: cc8be09472d9
Revises: 
Create Date: 2026-09-07 21:37:28.559275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8be09472d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_boards_public_id'), ['public_id'], unique=True)

    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_public_id'), ['public_id'], unique=True)

    op.create_table('board_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'image_id', name='uq_board_image')
    )
    with op.batch_alter_table('board_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_images_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_images_image_id'), ['image_id'], unique=False)

    op.create_table('image_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('style', sa.JSON(), nullable=False),
    sa.Column('mood', sa.JSON(), nullable=False),
    sa.Column('lighting', sa.Text(), nullable=False),
    sa.Column('composition', sa.Text(), nullable=False),
    sa.Column('color_palette', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('creative_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_analyses_image_id'), ['image_id'], unique=True)

    op.create_table('image_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_embeddings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_embeddings_image_id'), ['image_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_embeddings_image_id'))
        batch_op.drop_index(batch_op.f('ix_image_embeddings_id'))

    op.drop_table('image_embeddings')
    with op.batch_alter_table('image_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_analyses_image_id'))
        batch_op.drop_index(batch_op.f('ix_image_analyses_id'))

    op.drop_table('image_analyses')
    with op.batch_alter_table('board_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_images_image_id'))
        batch_op.drop_index(batch_op.f('ix_board_images_id'))
        batch_op.drop_index(batch_op.f('ix_board_images_board_id'))

    op.drop_table('board_images')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_public_id'))
        batch_op.drop_index(batch_op.f('ix_images_id'))

    op.drop_table('images')
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_public_id'))
        batch_op.drop_index(batch_op.f('ix_boards_id'))

    op.drop_table('boards')
    # ### end Alembic commands ###
